#
# Database
#
DB_BACKEND = "pymodm"
PYMODM_CONFIG = {"URI": "mongodb://localhost:27017/fhirbug"}
#
# Search
#
DEFAULT_BUNDLE_SIZE = 20
MAX_BUNDLE_SIZE = 100

MODELS_PATH = "examples.pymodm_autogenerated.mappings"

DEBUG = True
